version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      # ✅ FIX: ADD THIS LINE. This is the "await" you are looking for.
      # It tells Docker to give the backend a 300-second grace period to start up
      # before the healthcheck failures start counting.
      start_period: 300s
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy # This now waits for the patient healthcheck
    restart: always
    networks:
      - app-net

networks:
  app-net:
    driver: bridge